
services:
  # Base de datos con soporte para VECTORES (IA)
  postgres:
    image: pgvector/pgvector:pg16  # <--- IMPORTANTE: Usamos la imagen con pgvector
    container_name: network_psql
    environment:
      POSTGRES_DB: network   # <--- Verifica que coincida con tu application.properties
      POSTGRES_USER: postgres       # <--- Verifica
      POSTGRES_PASSWORD: 12345  # <--- Verifica
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Tu almacenamiento de imÃ¡genes (MinIO)
  minio:
    image: minio/minio
    container_name: network
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin      # <--- Verifica tus credenciales
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
